# Generated by Django 2.2 on 2020-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='This-is-my-first-post'),
            preserve_default=False,
        ),
    ]
