# Generated by Django 2.2 on 2020-09-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200907_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
